version: '3.9'
configs:
  sql_file_1:
    file: ./Database/hms.sql
services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
    links:
      - mysql_db
    networks:
      - default

  mysql_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    configs:
      - source: sql_file_1
        target: /sql/hms.sql
        mode: 444
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hms
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    links:
      - mysql_db:mysql_db
    #depends_on:
    # - mysql_db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql_db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
volumes:
  persistent: